language: python
services: docker

env:
  global:
    - ROLE_NAME: "vagrant"
  matrix:
    - MOLECULE_DISTRO: "ubuntu1804"

addons:
  apt:
    packages:
      - docker-ce

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker ansible
  - pip install 'molecule[docker]'

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME xat59.$ROLE_NAME
  - cd xat59.$ROLE_NAME

script:
  # Run tests.
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
